/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 3fNGqAggYY1nQYZkelimO0JcMI5vqvyOFxDsn3wVD/KG1TVCqskBzboCQNzs2Wc/DClmtpwfZF5GLxHXzwl0BA==
 */

/* eslint-disable */
// tslint:disable

import AtdatabasesMigrationsApplied, {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import AtdatabasesMigrationsVersion, {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import Member, {Member_InsertParameters} from './member'
import Org, {Org_InsertParameters} from './org'
import Site, {Site_InsertParameters} from './site'
import SiteAccess, {SiteAccess_InsertParameters} from './site_access'
import User, {User_InsertParameters} from './user'

interface DatabaseSchema {
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  member: {record: Member, insert: Member_InsertParameters};
  org: {record: Org, insert: Org_InsertParameters};
  site: {record: Site, insert: Site_InsertParameters};
  site_access: {record: SiteAccess, insert: SiteAccess_InsertParameters};
  user: {record: User, insert: User_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  Member,
  Member_InsertParameters,
  Org,
  Org_InsertParameters,
  Site,
  SiteAccess,
  SiteAccess_InsertParameters,
  Site_InsertParameters,
  User,
  User_InsertParameters,
}
