/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: gfhqnKjFOCGdKrGERUAiYjnafygX/SCRCyt4kPT0oXA5Euxwkg2KTwcivNL+8kGl6tyBM7HOvUgX/kcDo8eumA==
 */

/* eslint-disable */
// tslint:disable

import Org from './org'
import User from './user'

interface Member {
  created_at: Date
  /**
   * @default nextval('member_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'member_id'}
  is_disabled: boolean
  is_privileged: boolean
  name: string
  /**
   * @default nextval('member_org_id_seq'::regclass)
   */
  org_id: Org['id']
  updated_at: Date
  /**
   * @default nextval('member_user_id_seq'::regclass)
   */
  user_id: User['id']
}
export default Member;

interface Member_InsertParameters {
  created_at: Date
  /**
   * @default nextval('member_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'member_id'}
  is_disabled: boolean
  is_privileged: boolean
  name: string
  /**
   * @default nextval('member_org_id_seq'::regclass)
   */
  org_id?: Org['id']
  updated_at: Date
  /**
   * @default nextval('member_user_id_seq'::regclass)
   */
  user_id?: User['id']
}
export type {Member_InsertParameters}
