/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: VWlQHu+/j0+s8mz3nzlhOouTzWPyb/Oa2E8ohBCuJKItjBU+6+etpSttoM1Jlm15pXNh92mpfCV9uTn+NoWf3Q==
 */

/* eslint-disable */
// tslint:disable

import Member from './member'

interface Site {
  created_at: Date
  description: string
  /**
   * @default nextval('site_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'site_id'}
  is_anyone_joinable: boolean
  is_default: boolean
  is_disabled: boolean
  name: string
  /**
   * @default nextval('site_owner_id_seq'::regclass)
   */
  owner_id: Member['id']
  updated_at: Date
}
export default Site;

interface Site_InsertParameters {
  created_at: Date
  description: string
  /**
   * @default nextval('site_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'site_id'}
  is_anyone_joinable: boolean
  is_default: boolean
  is_disabled: boolean
  name: string
  /**
   * @default nextval('site_owner_id_seq'::regclass)
   */
  owner_id?: Member['id']
  updated_at: Date
}
export type {Site_InsertParameters}
