/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: IK5cQCkxNSpQ2CWYDwXb4SE7xHyH8wgsaOnaENdoC6i3bs9rqJTDJQw6vDCbJ6RpwA2KGPKyz3iuAEGCcs/BaA==
 */

/* eslint-disable */
// tslint:disable

interface User {
  created_at: Date
  email: string
  /**
   * @default nextval('user_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'user_id'}
  is_disabled: boolean
  is_email_verified: boolean
  is_mfa_enabled: boolean
  mfa: string
  name: string
  password: string
  updated_at: Date
}
export default User;

interface User_InsertParameters {
  created_at: Date
  email: string
  /**
   * @default nextval('user_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'user_id'}
  is_disabled: boolean
  is_email_verified: boolean
  is_mfa_enabled: boolean
  mfa: string
  name: string
  password: string
  updated_at: Date
}
export type {User_InsertParameters}
